baseURL = "http://www.funkycloudmedina.com/"
languageCode = "en-us"
title = "Funky Cloud Medina"
theme = "Blackburn"

author = "Stellios Williams"
# Shown in the side menu
copyright = "&copy; 2016-2017. All rights reserved."
canonifyurls = true
paginate = 10

[indexes]
  tag = "tags"
  topic = "topics"

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"
  preservetaxonomynames = true

[params]
  # Shown in the home page
  subtitle = "Getting funky with clouds."
  brand = "TheNewStellW"
  googleAnalytics = "Your Google Analytics tracking ID"
  # disqus = "Your Disqus shortname"
  # CSS name for highlight.js
  highlightjs = "androidstudio"
  highlightjs_extra_languages = ["yaml"]
  dateFormat = "02 Jan 2006"
  # Include any custom CSS and/or JS files
  # (relative to /static folder)
  custom_css = ["css/my.css"]
  custom_js = ["js/my.js"]

[permalinks]
  post = "/:year/:month/:title/"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 0
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 1
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 2
    identifier = "about"
    url = "/about/"
  [[menu.main]]
    name = "Contact"
    pre = "<i class='fa fa-phone fa-fw'></i>"
    weight = 3
    url = "/contact/"

[social]
  # Link your social networking accounts to the side menu
  # by entering your username or ID.

  # SNS microblogging
  twitter = "@TheNewStellW"
  # gnusocial = "*" # Specify href (e.g. https://quitter.se/yourusername)
  # facebook = "*"
  # googleplus = "*"
  # weibo = "*"
  # tumblr = "*"

  # SNS photo/video sharing
  # instagram = "*"
  # flickr = "*"
  # photo500px = "*"
  # pinterest = "*"
  # youtube = "*"
  # vimeo = "*"
  # vine = "*"
  # slideshare = "*"

  # SNS career oriented
  linkedin = "stellios-williams-2762153b"
  # xing = "*"

  # SNS news
  #reddit = "*"
  #hackernews = "*"

  # Techie
  github = "TheNewStellW"
  #gitlab = "*"
  #bitbucket = "*"
  #stackoverflow = "*"
  #serverfault = "*"

  # Gaming
  #steam = "*"
  #mobygames = "*"

  # Music
  #lastfm = "*"
  #discogs = "*"

  # Other
  #keybase = "*"